### ISSUE TITLE
Production build with CRA 5.0.0 fails due to postcss compilation error

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react-archive#4838]
## Issue summary

When using create-react-app 5.0.0 and attempting to perform a production build of the app using the standard build command, the build fails if you include the ESM styles like so:

```javascript
import "@shopify/polaris/build/esm/styles.css";
```

The failure is as follows:

```
Creating an optimized production build...
Failed to compile.

Syntax error: postcss-custom-properties: <css input> Unknown word (1:1)
> 1 | -50% + var(--Polaris-RangeSlider-output-factor)*var(--p-range-slider-thumb-size-base)
    | ^
```

## Expected behavior

A production build successfully runs.

## Actual behavior

An error is thrown from postcss on the following line from the styles.css ESM import:

```css
.Polaris-RangeSlider-SingleThumb__Output { position: absolute; z-index: 20; bottom: var(--p-range-slider-thumb-size-base); left: var(--Polaris-RangeSlider-progress); transform: translateX(calc(-50% + var(--Polaris-RangeSlider-output-factor)*var(--p-range-slider-thumb-size-base))); opacity: 0; visibility: hidden; pointer-events: none; transition-property: opacity, visibility, bottom; transition-duration: 200ms; transition-timing-function: cubic-bezier(0.25, 0.1, 0.25, 1); }
```

Pretty print version:
```css
.Polaris-RangeSlider-SingleThumb__Output {
	position: absolute;
	z-index: 20;
	bottom: var(--p-range-slider-thumb-size-base);
	left: var(--Polaris-RangeSlider-progress);
	transform: translateX(calc(-50% + var(--Polaris-RangeSlider-output-factor)*var(--p-range-slider-thumb-size-base)));
	opacity: 0;
	visibility: hidden;
	pointer-events: none;
	transition-property: opacity, visibility, bottom;
	transition-duration: 200ms;
	transition-timing-function: cubic-bezier(0.25, 0.1, 0.25, 1);
}
```

Looking at the output it looks valid to me, but perhaps I'm missing something. I checked it against a CSS validator and it passed, so this may be a postcss bug.

## Steps to reproduce the problem

1. Install create-react-app 5.0.0
1. Run `create-react-app polaris-test`
2. Add Polaris to the dependencies: `yarn add @shopify/polaris`
3. At the top of the `index.js` file, add the line: `import "@shopify/polaris/build/esm/styles.css";`
4. Run `yarn build`

## Reduced test case

The steps mentioned above work as a reduced test case. I'm not aware of how to provide it with a codesandbox that also performs a production build.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 7.5.0
- Browser: N/A
- Device: MacBook Pro M1
- Operating System: macOS Monterey 12.1

**Comment by mbaumbach** [comment]
The issue seems to stem from the multiplication between the `var` custom properties. If you add spaces around the asterisk, it builds successfully. So changing that line to the following corrects things:

```
.Polaris-RangeSlider-SingleThumb__Output { position: absolute; z-index: 20; bottom: var(--p-range-slider-thumb-size-base); left: var(--Polaris-RangeSlider-progress); transform: translateX(calc(-50% + var(--Polaris-RangeSlider-output-factor) * var(--p-range-slider-thumb-size-base))); opacity: 0; visibility: hidden; pointer-events: none; transition-property: opacity, visibility, bottom; transition-duration: 200ms; transition-timing-function: cubic-bezier(0.25, 0.1, 0.25, 1); }
```

The affected line is https://github.com/Shopify/polaris-react/blob/741eeb6834d6a2f9a5ff8eca86a7b1a05dd684fe/src/components/RangeSlider/components/SingleThumb/SingleThumb.scss#L163. It already has a space in this particular area, so I'm not sure what's removing it. Again, I think this is really a postcss bug, but if it's possible to fix it in Polaris with a simple change, it might reduce some friction for end users. I'm not sure what build process Polaris may be using which would be stripped that space out.

**Comment by mbaumbach** [comment]
I also [opened a bug report](https://github.com/postcss/postcss-custom-properties/issues/261) with the project that seems to be throwing the error, though it may be more deeply nested than that.

**Comment by kyledurand** [comment]
@BPScott @chloerice have we seen something similar before? For some reason it's ringing bells but I forget the actual issue

**Comment by chloerice** [comment]
Hmmm I haven't seen something like this, at least not that I can remember 🤔 When I was reading through the issue I assumed it was failing because it needs to be wrapped in `calc` 👀 It's odd that spaces around the asterisk would be the only fix needed 🧐

**Comment by BPScott** [comment]
#441 and #2629 are the blasts from the past you're thinking of.

Sounds like another bug in `postcss/postcss-custom-properties`. Thank you @mbaumbach for already raising the issue upstream. It'd be worth confirming if this issue is still present in the latest version of `postcss-custom-properties` as in the past we had these problems as CRA was using an old version of `postcss-custom-properties` but the issue was fixed in the latest version. I spy CRA has started using `^` for its dependencies rather than locking them so I'm hopeful that an actual bug that needs to be fixed rather than just CRA being outdated.

**Comment by mbaumbach** [comment]
I can confirm that I'm using the latest release of `postcss-custom-properties` (v12.0.0) which is what CRA 5.0.0 pulled in, so hopefully a fix there will mean a quick update or `resolutions` override can correct the issue.

**Comment by mbaumbach** [comment]
There's a new release of `postcss-custom-properties` (v12.0.1) which seems to fix this.
